# Generated by Django 5.2.4 on 2025-08-15 15:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('post_owner_reddit_username', models.CharField(db_index=True, max_length=100)),
                ('reddit_post_id', models.CharField(max_length=20, unique=True)),
                ('post_url', models.URLField()),
                ('post_title', models.CharField(max_length=300)),
                ('post_category', models.CharField(blank=True, max_length=100, null=True)),
                ('desired_skills', models.TextField(blank=True, null=True)),
                ('post_trigger', models.CharField(blank=True, choices=[('task', 'Task'), ('offer', 'Offer'), ('unspecific', 'Unspecific')], default='unspecific', max_length=20, null=True)),
                ('subreddit', models.CharField(db_index=True, max_length=100)),
                ('post_time', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'verbose_name': 'Reddit Post',
                'verbose_name_plural': 'Reddit Posts',
                'db_table': 'posts',
                'ordering': ['-post_time'],
            },
        ),
    ]
