# Generated by Django 5.2.4 on 2025-08-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_post_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_owner_reddit_username',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
