# Generated by Django 5.2.4 on 2025-08-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_post_owner_reddit_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_trigger',
            field=models.CharField(blank=True, choices=[('task', 'Task'), ('offer', 'Offer'), ('unspecific', 'Unspecific')], default='unspecific', max_length=20, null=True),
        ),
    ]
