# Generated by Django 5.2.4 on 2025-08-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_post_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='desired_skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
